//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrhhMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public Cargos()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public string IdCargo { get; set; }
        public string DescripcionCargo { get; set; }
    
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
