//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rrhhMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public string IdEmpleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string DocumentoId { get; set; }
        public byte[] Foto { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IdSupervisor { get; set; }
        public string IdCargo { get; set; }
        public string IdTipoEmpleado { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoMovil { get; set; }
        public string Direccion { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
